services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/media:/vol/web/media
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - backend/.env
    volumes:
      - my-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  my-db:
  my_media:
