# Generated by Django 5.1 on 2024-08-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barmeister", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cocktailrecipe",
            name="quantity",
        ),
    ]
