# Generated by Django 5.1 on 2024-08-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barmeister", "0003_alter_ingredient_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("gr", "G"),
                    ("ml", "Ml"),
                    ("slice", "Slice"),
                    ("pcs", "Piece"),
                ],
                max_length=50,
            ),
        ),
    ]
