# Generated by Django 5.1 on 2024-08-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barmeister", "0004_alter_ingredient_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktailrecipe",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
