# Generated by Django 5.1 on 2024-08-30 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barmeister", "0006_remove_cocktailrecipe_updated_at_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cocktailrecipe",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-commented_at"]},
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("gr", "G"),
                    ("ml", "Ml"),
                    ("slice", "Slice"),
                    ("pcs", "Piece"),
                    ("tablespoon", "Tablespoon"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="FavouriteCocktails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourites",
                        to="barmeister.cocktailrecipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "unique_together": {("user", "cocktail")},
            },
        ),
    ]
