import { Ingridients } from "../types/componentsType";

export const popularComponents: Ingridients[] = [
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#redWine',
    componentName: 'Red wine',
    ingridientName: 'redwine',
    ingridientCategory: 'Wine and champagne',
    ingridientOrigin: 'France, Italy, Spain',
    ingridientInvented: 'Unknown',
    ingridientStrenght: '13%',
    ingridientBackgroundImg: 'img/ShakeIngridients/redWine.jpg',
    ingridientDescription: 'Red wine is a type of alcoholic beverage made from fermented dark-colored grapes. It typically has a rich, robust flavor and can vary in sweetness and tannin levels. In cocktails and mixology, red wine is often used as a base or ingredient to add depth and complexity to drinks. It can bring fruitiness, acidity, and earthy notes to a variety of cocktails, from traditional classics to modern creations. It is also popularly used in sangrias and wine-based punches, adding color and flavor to these refreshing beverages. Red wine is a versatile and essential component in the world of mixology, adding a sophisticated touch to any cocktail.',
    componentText: "Welcome to our vibrant collection of exquisite cocktails made with Red Wine, your go-to destination for discovering the perfect blend of flavors. Dive into our recipes that artfully combine Red Wine with an array of ingredients, offering a delightful twist to your beverage repertoire. Whether you’re searching for a bold Sangria, a refreshing Spritzer, or an enchanting Red Wine cocktail, our curated selections promise to inspire your mixology skills. Perfect for any occasion, these Red Wine concoctions are sure to impress your guests and elevate your entertaining game. Cheers to exploring the rich, versatile world of Red Wine cocktails!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#sherrySweet',
    componentName: 'Sherry(Sweet)',
    ingridientName: 'sherrysweet',
    ingridientCategory: 'Wine and champagne',
    ingridientOrigin: 'Spain',
    ingridientInvented: '16th century',
    ingridientStrenght: '18%',
    ingridientBackgroundImg: 'img/ShakeIngridients/sherrySweet.webp',
    ingridientDescription: 'Sherry, also known as Sweet Sherry, is a fortified wine made from white grapes that are grown in the Andalusia region of southern Spain. This versatile and flavorful wine is often used in cocktails and mixology for its sweet and nutty flavors, adding depth and complexity to drinks. Its use in cocktails dates back centuries, making it a beloved ingredient in the world of mixology. Depending on the style of Sherry, it can add a range of flavors such as dried fruits, caramel, and spices to cocktails, making it a must-have ingredient for any mixologist.',
    componentText: "Welcome to our delightful collection of sweet Sherry cocktail recipes, where each sip promises a journey into exquisiteness! If you're eager to explore the world of cocktail crafting, you've come to the perfect spot. Our curated list features the best Sherry-based concoctions, designed for both beginners and connoisseurs alike. Dive into our easy-to-follow recipes, tips, and tricks that cater to every taste, ensuring your home bar becomes the talk of the town. Whether you're after a cozy night in or planning to dazzle guests, our sweet Sherry cocktails are your ticket to an unforgettable experience. Cheers to mixing up elegance and fun in every glass!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#Lemon',
    componentName: 'Lemon',
    ingridientName: 'lemon',
    ingridientCategory: 'Kitchen cupboard',
    ingridientOrigin: '',
    ingridientInvented: '',
    ingridientStrenght: '0%',
    ingridientBackgroundImg: 'img/ShakeIngridients/lemon.jpg',
    ingridientDescription: 'Lemon is a versatile and zesty citrus fruit that is commonly used in cocktails and mixology. Its tart and tangy flavor adds depth and brightness to drinks, making it a popular ingredient among bartenders. Lemon is typically used in the form of fresh juice or wedges, which are then muddled or squeezed into cocktails to balance out sweet or bitter flavors. It also adds a refreshing and citrusy aroma to drinks, making it a staple in classic cocktails such as the martini, margarita, and whiskey sour. Its acidity and citrus oils play a crucial role in enhancing the overall taste and aroma of cocktails, making lemon an essential ingredient in mixology.',
    componentText: "Dive into the zesty world of cocktails with lemon juice, your ultimate go-to ingredient for that perfect tang in every sip! From refreshing summer classics to cozy winter warmers, lemon juice adds just the right amount of zest, making your beverages irresistibly delicious. Ideal for those seeking to elevate their mixology skills or simply enjoy a delightful twist in their drinks, our collection features easy-to-follow, versatile recipes that are sure to impress. Whether you're a seasoned cocktail connoisseur or a curious beginner, discover how to blend the perfect lemony concoction today!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#lime',
    componentName: 'Lime juice',
    ingridientName: 'lime-juice',
    ingridientCategory: 'Kitchen cupboard',
    ingridientOrigin: '',
    ingridientInvented: '',
    ingridientStrenght: '0%',
    ingridientBackgroundImg: 'img/ShakeIngridients/limeJuice.jpg',
    ingridientDescription: 'Lime juice is a tart and citrusy liquid that is extracted from the tangy fruit. It is a common ingredient in cocktails and mixology, adding a refreshing and zesty kick to drinks. The juice is typically squeezed directly from the fruit or bottled as a concentrated or pre-squeezed liquid, making it easily accessible for use in mixology. Its bright and tangy flavor pairs well with a variety of alcoholic and non-alcoholic beverages, making it a versatile and essential ingredient in cocktail making. Its acidity also helps to balance out the sweetness of other ingredients, creating a well-rounded and flavorful drink.',
    componentText: "Discover the zesty world of lime juice cocktails, where every sip is a refreshing adventure! Perfect for summer days, cozy winter evenings, or any special occasion in between, lime juice is the versatile superstar that brings life to your drink. Whether you're a fan of classics or eager to explore new, creative mixes, our collection features the best lime-infused concoctions. If you're diving into homemade mixology or searching for the perfect lime juice cocktail recipe to impress your guests, you've landed in the right place. Cheers to exploring the vibrant burst of flavors lime juice has to offer!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#cachaca',
    componentName: 'Cachaça',
    ingridientName: 'cachaca',
    ingridientCategory: 'Spirit',
    ingridientOrigin: 'Brazil',
    ingridientInvented: 'Generic: Unknown/ancient/traditional',
    ingridientStrenght: '40%',
    ingridientBackgroundImg: 'img/ShakeIngridients/cachaça.jpg',
    ingridientDescription: 'Cachaça is a Brazilian distilled spirit made from fermented sugarcane juice. It has a distinct herbal and fruity flavor and is often compared to rum. In cocktails and mixology, cachaça is commonly used as a base spirit in drinks like the Caipirinha and Batida, but it can also be used as a substitute for other spirits in classic cocktails. Its unique flavor and versatility make it a popular choice for creating refreshing and flavorful cocktails.',
    componentText: "Discover the vibrant world of Cachaça cocktails, where each sip promises a journey to the heart of Brazilian culture. Whether you're an aspiring mixologist or a seasoned connoisseur, our collection is a treasure trove of recipes featuring this distinctive spirit. Distinguished by its raw, sugarcane essence, Cachaça offers a versatile foundation for a myriad of refreshing creations. From classic favorites to innovative concoctions, let's explore the rich flavors and intoxicating aromas of cocktails made with Cachaça. Say 'saúde' and dive into our handpicked selection, sure to elevate your home bartending game.",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#gin-tonic',
    componentName: 'Gin',
    ingridientName: 'gin',
    ingridientCategory: 'spirit',
    ingridientOrigin: 'England, Netherlands',
    ingridientInvented: '17th century',
    ingridientStrenght: '40%',
    ingridientBackgroundImg: 'img/ShakeIngridients/gin.jpg',
    ingridientDescription: 'Gin is a clear alcoholic spirit that is distilled from grains and flavored with botanicals such as juniper berries, coriander, and citrus peel. It has a distinctive and complex flavor profile that ranges from herbal and spicy to floral and citrusy. It is commonly used in cocktails and mixology because its unique flavor adds depth and complexity to drinks. From classic cocktails like the gin and tonic to modern creations, gin is a versatile and essential ingredient that adds a bold and refreshing element to any mixed drink. Whether shaken, stirred, or even sipped neat, gin is a staple in the world of mixology.',
    componentText: "Welcome to our delightful corner of the internet, where gin enthusiasts and cocktail aficionados unite in their pursuit of discovering the perfect gin-based concoction. Whether you're in search of a refreshing summer sipper or a cozy winter warmer, our extensive collection of gin cocktail recipes promises to elevate your mixology game. From classic favorites to innovative creations, each recipe is crafted to inspire and impress. Dive into the world of botanical infusions, where the juniper-forward spirit meets its match in a symphony of flavors. Let’s shake, stir, and savor the best gin cocktails together!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#frangelico',
    componentName: 'Frangelico',
    ingridientName: 'frangelico',
    ingridientCategory: 'Liqueur',
    ingridientOrigin: 'Italy',
    ingridientInvented: '19th century',
    ingridientStrenght: '20%',
    ingridientBackgroundImg: 'img/ShakeIngridients/frangelico.webp',
    ingridientDescription: "Frangelico is a sweet and nutty liqueur that is commonly used in cocktails and mixology. Its distinct flavor comes from a combination of hazelnuts, cocoa, and vanilla, giving it a smooth and rich taste. This versatile spirit is often mixed with other ingredients such as coffee, chocolate, or cream to create delicious cocktails or added as a flavorful ingredient in a variety of cocktails. With its unique taste and versatility, Frangelico is a beloved addition to any mixologist's bar and a must-have for creating delicious and creative cocktails.",
    componentText: "Welcome to the world of divine cocktails featuring Frangelico, the enchanting hazelnut liqueur that promises to elevate your mixology game. Whether you're a seasoned bartender or a home cocktail enthusiast, our curated collection of Frangelico cocktail recipes is set to inspire. From the luxurious velvet texture to the rich nutty flavor, Frangelico seamlessly blends into an array of drink creations, making it a favorite among cocktail aficionados. Dive into our guide, packed with tips, techniques, and the perfect recipes to showcase the versatility and charm of Frangelico in your next drink. Cheers to unforgettable concoctions!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#bourbon',
    componentName: 'Bourbon',
    ingridientName: 'bourbon',
    ingridientCategory: 'Spirit',
    ingridientOrigin: 'United States',
    ingridientInvented: '1789',
    ingridientStrenght: '40%',
    ingridientBackgroundImg: 'img/ShakeIngridients/bourbon.jpg',
    ingridientDescription: 'Bourbon is a type of American whiskey that is made mostly from corn and aged in charred oak barrels. It has a smooth and slightly smoky flavor with hints of vanilla, caramel, and oak. Its versatility makes it a staple in cocktails and mixology, adding depth and complexity to drinks. Its rich and bold flavor profile pairs well with a variety of ingredients, making it a go-to for classic cocktails such as the Old Fashioned, Manhattan, and Whiskey Sour. Its popularity in mixology has also spurred the creation of newer, innovative cocktails that showcase its distinct taste and character.',
    componentText: "Dive into the rich and velvety world of Bourbon cocktails, where tradition meets tantalizing taste in every sip. Whether you're a seasoned mixologist or stepping into the art of cocktail making for the first time, our collection has something special for you. From classic concoctions to innovative twists, discover the best Bourbon cocktail recipes that will elevate your gatherings and impress your palate. Explore the magic of this beloved whiskey ingredient and let it inspire your next home bar adventure. Cheers to discovering your new favorite Bourbon-infused delight!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#coffee-liqueur',
    componentName: 'Coffee liqueur',
    ingridientName: 'coffee-liqueur',
    ingridientCategory: 'Liqueur',
    ingridientOrigin: 'Mexico, Italy, Ireland',
    ingridientInvented: '1951',
    ingridientStrenght: '20%',
    ingridientBackgroundImg: 'img/ShakeIngridients/coffee-liqueur.jpg',
    ingridientDescription: 'Coffee liqueur is a sweet and indulgent alcoholic beverage made from a combination of coffee beans, sugar, and distilled spirits. Its rich, dark flavor and smooth texture make it a popular ingredient in cocktails and mixology, adding depth and complexity to drinks such as the classic White Russian or Espresso Martini. It can also be used as a versatile base for creating unique coffee-infused cocktails and is often used as a topping or drizzle on desserts and ice cream for an extra kick of flavor. Whether shaken, stirred, or poured, coffee liqueur is an essential component in elevating the taste and experience of a cocktail.',
    componentText: "Dive into the indulgent world of cocktails made with coffee liqueur, a must-try for enthusiasts seeking the ultimate nightcap or a sophisticated sip to jazz up their evenings. Our curated selection offers an exquisite blend of velvety coffee flavors and spirited creativity, perfect for every occasion. Whether you're in the mood for something classic or craving an innovative twist, our recipes promise to satisfy your desires with every sip. Explore and discover how to make these heavenly concoctions at home, turning ordinary gatherings into extraordinary memories. Cheers to exploring the art of coffee liqueur cocktails together!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#cranberry-juice',
    componentName: 'Cranberry juice',
    ingridientName: 'cranberry-juice',
    ingridientCategory: 'Mixer',
    ingridientOrigin: 'United States, Canada',
    ingridientInvented: '17th century',
    ingridientStrenght: '0%',
    ingridientBackgroundImg: 'img/ShakeIngridients/cranberryJuice.jpg',
    ingridientDescription: "Cranberry juice is a tart and refreshing beverage commonly used in cocktails and mixology. Made from the juice of cranberries, it adds a burst of vibrant flavor and a hint of sweetness to any drink. Its tangy taste and deep red color make it a versatile ingredient that pairs well with a variety of spirits, from vodka to tequila. Whether it's in a classic Cosmopolitan or a modern twist on a Margarita, cranberry juice is a must-have for any mixologist looking to add a zingy kick to their creations. Its versatility and ability to balance flavors make it a popular choice for both amateur and professional bartenders alike.",
    componentText: "Dive into the vibrant world of cocktails made with the tangy twist of cranberry juice, a popular choice for mixologists and home bartenders alike! Whether you're in the mood for a refreshing cocktail on a sunny afternoon or crafting the perfect drink to impress at your next gathering, cranberry juice offers a versatile base that pairs beautifully with a wide range of spirits and ingredients. From classic favorites to innovative creations, explore our curated selection of cranberry juice cocktail recipes, guaranteed to tantalize your taste buds and elevate your home bartending skills. Cheers to discovering your next go-to drink!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#raspberry_liqueuer',
    componentName: 'Raspberry liqueur',
    ingridientName: 'raspberry-liqueuer',
    ingridientCategory: 'Liqueur',
    ingridientOrigin: 'France, United States, Germany',
    ingridientInvented: '1958',
    ingridientStrenght: '15%',
    ingridientBackgroundImg: 'img/ShakeIngridients/raspberry-liqueur.webp',
    ingridientDescription: 'Raspberry liqueur is a sweet and tangy spirit infused with the vibrant flavors of ripe raspberries. Made from raspberries, sugar, and alcohol, this liqueur is a staple in cocktails and mixology due to its versatile and fruity profile. Its bright color and intense berry taste add depth and complexity to cocktails, making it a favorite among bartenders and mixologists. Whether used as a main ingredient or a finishing touch, Raspberry liqueur is sure to elevate any cocktail to a new level of deliciousness.',
    componentText: "Dive into the vibrant world of raspberry liqueur cocktails, the perfect blend of sweet and tart to elevate your mixology game. Explore our curated list of easy-to-follow recipes, designed for both beginner and seasoned cocktail enthusiasts. Whether you're hosting a classy soirée or simply unwinding after a long day, our collection showcases the versatility of raspberry liqueur, promising to add a splash of color and a burst of flavor to your drink repertoire. Get ready to shake, stir, and sip your way through the best raspberry liqueur cocktails that are sure to impress your guests and delight your taste buds. Cheers to discovering your new favorite concoction!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#apple-juice',
    componentName: 'Apple juice',
    ingridientName: 'apple-juice',
    ingridientCategory: 'Mixer',
    ingridientOrigin: 'United States, China, Poland',
    ingridientInvented: '1873',
    ingridientStrenght: '0%',
    ingridientBackgroundImg: 'img/ShakeIngridients/apple-juice.jpg',
    ingridientDescription: 'Apple juice is a refreshing and versatile beverage made from the juice of crushed apples. It has a sweet and tangy flavor, and a smooth texture that pairs well with a variety of ingredients. In cocktails and mixology, apple juice is often used as a base for creating unique and flavorful drinks, adding a fruity and slightly tart element. Its natural sweetness can compliment a range of spirits, making it a popular choice for refreshing spritzers, fruity martinis, and other creative concoctions.',
    componentText: "Apple juice is a refreshing and versatile beverage made from the juice of crushed apples. It has a sweet and tangy flavor, and a smooth texture that pairs well with a variety of ingredients. In cocktails and mixology, apple juice is often used as a base for creating unique and flavorful drinks, adding a fruity and slightly tart element. Its natural sweetness can compliment a range of spirits, making it a popular choice for refreshing spritzers, fruity martinis, and other creative concoctions.",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#port',
    componentName: 'Port',
    ingridientName: 'port',
    ingridientCategory: 'Wine and champagne',
    ingridientOrigin: 'Portugal',
    ingridientInvented: '18th century',
    ingridientStrenght: '18%',
    ingridientBackgroundImg: 'img/ShakeIngridients/port.jpg',
    ingridientDescription: 'Port is a fortified wine that is traditionally produced in the Douro Valley of Portugal. It is typically served as an after-dinner drink due to its sweet and rich flavor. In cocktails and mixology, port is often used as a base spirit or as a finishing touch, adding depth and complexity to the drink. Its fruity and full-bodied nature pairs well with other spirits and ingredients, making it a versatile addition to any cocktail recipe. It can also be enjoyed on its own as a digestif, slowly sipped and savored.',
    componentText: "Dive into the enchanting world of cocktails made with Port, the sumptuous wine that brings a unique depth and sweetness to your drink concoctions. Whether you're looking to elevate your home bartending skills or simply exploring new mixology landscapes, our collection features an array of Port cocktails that cater to every palate. From classic blends to innovative creations, discover how this versatile ingredient can transform your cocktail recipes. Perfect for cozy evenings, special occasions, or as a delightful way to impress your guests, let Port inspire your next mixology adventure. Cheers to exploring the rich flavors and aromas of Port-infused cocktails!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#pear',
    componentName: 'Pear',
    ingridientName: 'pear',
    ingridientCategory: 'Kitchen cupboard',
    ingridientOrigin: '',
    ingridientInvented: '',
    ingridientStrenght: '0%',
    ingridientBackgroundImg: 'img/ShakeIngridients/pear.jpg',
    ingridientDescription: 'Pear, also known as Pyrus communis, is a delicious and versatile fruit commonly used in cocktails and mixology. Its juicy and sweet flavor pairs well with a variety of spirits such as vodka, gin, and whiskey. Pear can be incorporated into cocktails in many forms including pear juice, puree, and slices, adding a natural sweetness and refreshing touch to the drink. With its unique flavor profile, pear is a popular ingredient in many classic and modern cocktail recipes, making it a staple in mixology.',
    componentText: "Pear, also known as Pyrus communis, is a delicious and versatile fruit commonly used in cocktails and mixology. Its juicy and sweet flavor pairs well with a variety of spirits such as vodka, gin, and whiskey. Pear can be incorporated into cocktails in many forms including pear juice, puree, and slices, adding a natural sweetness and refreshing touch to the drink. With its unique flavor profile, pear is a popular ingredient in many classic and modern cocktail recipes, making it a staple in mixology.",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#red-vermouth',
    componentName: 'Red vermouth',
    ingridientName: 'red-vermouth',
    ingridientCategory: 'Wine and champagne',
    ingridientOrigin: 'Italy, France, Spain',
    ingridientInvented: '1850s',
    ingridientStrenght: '16%',
    ingridientBackgroundImg: 'img/ShakeIngridients/vermouth.jpg',
    ingridientDescription: "Red vermouth is a type of fortified wine that is typically spiced and slightly sweetened with a variety of herbs, fruits, and spices. It is used in cocktails and mixology as a versatile ingredient to add depth and complexity to drinks. Its distinct flavors and aromas make it a popular choice for both classic and modern recipes, and it can be used as a base spirit or a modifier in a wide range of cocktails. Its rich, reddish color adds a beautiful hue to drinks and enhances their overall appearance. Whether it's sipped on its own or mixed into a cocktail, red vermouth adds a unique and sophisticated element to any drink.",
    componentText: "Welcome to our vibrant and flavorful world where Red Vermouth takes center stage in crafting captivating cocktails! Whether you're a mixology enthusiast searching for the perfect happy hour concoction or a beginner eager to explore the depths of this aromatic fortified wine, you've landed in the right place. Our curated selection features an array of recipes, each designed to showcase the versatility and rich taste of Red Vermouth. Dive into our collection, where classic meets contemporary, and discover your new favorite Red Vermouth cocktail to impress guests or savor during a tranquil evening at home.",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#pineapple-rum',
    componentName: 'Pineapple rum',
    ingridientName: 'pineapple-rum',
    ingridientCategory: 'Spirit',
    ingridientOrigin: 'Caribbean',
    ingridientInvented: '1840s',
    ingridientStrenght: '40%',
    ingridientBackgroundImg: 'img/ShakeIngridients/pineapple-rum.webp',
    ingridientDescription: 'Pineapple rum is a tropical and fruity spirit that combines the sweet and tangy flavors of pineapple with the smoothness of rum. It is often used in cocktails and mixology to add a refreshing and tropical twist to classic rum drinks, such as the piña colada or mojito. Its fruity notes and subtle sweetness make it a versatile ingredient that can be used to create a variety of tropical-inspired cocktails, perfect for sipping on a hot summer day or adding a splash of sunshine to any drink. Whether shaken or stirred, pineapple rum adds a burst of flavor and is a staple in the world of cocktails and mixology.',
    componentText: "Pineapple rum is a tropical and fruity spirit that combines the sweet and tangy flavors of pineapple with the smoothness of rum. It is often used in cocktails and mixology to add a refreshing and tropical twist to classic rum drinks, such as the piña colada or mojito. Its fruity notes and subtle sweetness make it a versatile ingredient that can be used to create a variety of tropical-inspired cocktails, perfect for sipping on a hot summer day or adding a splash of sunshine to any drink. Whether shaken or stirred, pineapple rum adds a burst of flavor and is a staple in the world of cocktails and mixology.",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#sugar',
    componentName: 'Sugar syrup',
    ingridientName: 'sugar',
    ingridientCategory: 'Mixer',
    ingridientOrigin: 'Brazil, India, Thailand',
    ingridientInvented: '',
    ingridientStrenght: '0%',
    ingridientBackgroundImg: 'img/ShakeIngridients/sugar-syrup.jpg',
    ingridientDescription: 'Sugar syrup, also known as simple syrup, is a key ingredient in cocktails and mixology. Made from a combination of sugar and water, sugar syrup adds sweetness and balance to drinks, without the grainy texture of regular sugar. It is a versatile ingredient that dissolves easily, making it perfect for creating well-balanced and consistent flavors in cocktails. Whether used as a sweetener or to create syrups infused with various flavors, sugar syrup is an essential element in the world of mixology, contributing to the overall taste and texture of drinks.',
    componentText: "Discover the sweet symphony of cocktails made with sugar, your essential guide to crafting delightful libations that tantalize the taste buds. From the velvety smoothness of simple syrups to the caramel whispers of demerara, sugar elevates each sip into a celebration of flavors. Whether you’re a mixology maestro or a cocktail connoisseur, our collection of sugar-based drink recipes promises to inspire your next gathering. Embrace the art of cocktail making with our expert tips, tricks, and ingredients, and let the magic of sugar-infused beverages enchant your evenings. Cheers to sweet, spirited adventures!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#orange-vodka',
    componentName: 'Orange vodka',
    ingridientName: 'orange-vodka',
    ingridientCategory: 'Spirit',
    ingridientOrigin: 'France, United States',
    ingridientInvented: '1990s',
    ingridientStrenght: '40%',
    ingridientBackgroundImg: 'img/ShakeIngridients/orange-vodka.webp',
    ingridientDescription: 'Orange vodka is a versatile and popular spirit that is infused with natural or artificial orange flavors, resulting in a bright and refreshing taste. Its vibrant orange hue and citrusy notes make it a staple in many classic as well as modern cocktails. Its ability to enhance other ingredients and add a hint of sweetness makes it a favorite among mixologists, who use it to create innovative and flavorful drinks. From simple screwdrivers to complex martinis, orange vodka adds a zesty and enticing twist to any cocktail, making it a must-have in any well-stocked bar.',
    componentText: "Orange vodka is a versatile and popular spirit that is infused with natural or artificial orange flavors, resulting in a bright and refreshing taste. Its vibrant orange hue and citrusy notes make it a staple in many classic as well as modern cocktails. Its ability to enhance other ingredients and add a hint of sweetness makes it a favorite among mixologists, who use it to create innovative and flavorful drinks. From simple screwdrivers to complex martinis, orange vodka adds a zesty and enticing twist to any cocktail, making it a must-have in any well-stocked bar.",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#champagne',
    componentName: 'Champagne / prosecco',
    ingridientName: 'champagne-prosecco',
    ingridientCategory: 'Wine and champagne',
    ingridientOrigin: 'France',
    ingridientInvented: '17th century',
    ingridientStrenght: '12%',
    ingridientBackgroundImg: 'img/ShakeIngridients/champagne.jpg',
    ingridientDescription: 'Champagne is a sparkling wine that is traditionally produced in the Champagne region of France. It is made from specific varietals of grapes, namely Chardonnay, Pinot Noir, and Pinot Meunier, and is known for its effervescence and crisp, dry taste. Champagne is often used in cocktails and mixology to add a touch of elegance and celebration to drinks. Its bubbles and unique flavor profile make it a popular ingredient in classic cocktails like mimosas and French 75s, as well as more modern creations. The versatility of champagne in mixology allows for endless possibilities in creating delicious and sophisticated drinks.',
    componentText: "Welcome to the sparkling world of Champagne and Prosecco cocktails, where elegance meets effervescence in every sip! Whether you're hosting a festive celebration or looking for the perfect bubbly concoction to elevate your weekend, our collection of recipes is your ultimate guide. Delve into the art of mixing these prestigious beverages to craft delightful drinks that'll impress any guest. From the classic elegance of a mimosa to the refreshing twist of a spritz, discover the secrets to creating unforgettable Champagne and Prosecco cocktails that are bound to become your go-to favorites. Cheers to the perfect pour!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#cherry',
    componentName: 'Maraschino cherry',
    ingridientName: 'cherry',
    ingridientCategory: 'Kitchen cupboard',
    ingridientOrigin: '',
    ingridientInvented: '',
    ingridientStrenght: '0%',
    ingridientBackgroundImg: 'img/ShakeIngridients/maraschino-cherry.jpg',
    ingridientDescription: 'Maraschino cherries are a beloved ingredient in cocktails and mixology, prized for their bright red color and sweet, tangy flavor. These cherries are typically made from a specific type of cherry, the Luxardo cherry, which is soaked in a rich syrup made from the pits and stems of the fruit. Once removed from the syrup and dried, Maraschino cherries are then commonly used as a garnish in a variety of cocktails, adding a touch of sweetness and visual appeal to drinks. They can also be muddled or used as a flavoring in syrups and sauces to add a unique twist to traditional cocktails.',
    componentText: "Maraschino cherries are a beloved ingredient in cocktails and mixology, prized for their bright red color and sweet, tangy flavor. These cherries are typically made from a specific type of cherry, the Luxardo cherry, which is soaked in a rich syrup made from the pits and stems of the fruit. Once removed from the syrup and dried, Maraschino cherries are then commonly used as a garnish in a variety of cocktails, adding a touch of sweetness and visual appeal to drinks. They can also be muddled or used as a flavoring in syrups and sauces to add a unique twist to traditional cocktails.",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#tequila',
    componentName: 'Tequila',
    ingridientName: 'tequila',
    ingridientCategory: 'Spirit',
    ingridientOrigin: 'Mexico',
    ingridientInvented: '1590',
    ingridientStrenght: '40%',
    ingridientBackgroundImg: 'img/ShakeIngridients/tequila.webp',
    ingridientDescription: 'Tequila is a distilled spirit that originates from the agave plant in Mexico. It is known for its unique flavor profile, ranging from earthy and vegetal to sweet and citrusy, making it a popular choice for cocktails and mixology. Tequila is commonly used in classic drinks such as the margarita and paloma, as well as creative concoctions that highlight its versatility and complexity. The different types of tequila, including blanco, reposado, and añejo, offer a wide range of flavors and aromas that can enhance any cocktail experience. With its rich history and distinct taste, tequila continues to be a staple ingredient in the world of mixology.',
    componentText: "Discover the vibrant world of tequila cocktails on our ultimate recipe page, where the spirit of Mexico transforms into liquid magic in your glass. Whether you're searching for the perfect margarita, eager to explore tequila sunrise variants, or ready to dive into a paloma, we've curated the best recipes that celebrate this agave-based wonder. From classic concoctions to modern mixes, our collection is your go-to guide for crafting delightful tequila drinks that promise to elevate any occasion. Join us as we shake, stir, and sip our way through the exciting realm of tequila cocktails.",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#peppermint-Liqueur',
    componentName: 'Peppermint Liqueur',
    ingridientName: 'peppermint-liqueur',
    ingridientCategory: 'Liqueur',
    ingridientOrigin: 'Italy, France',
    ingridientInvented: '1800s',
    ingridientStrenght: '15%',
    ingridientBackgroundImg: 'img/ShakeIngridients/peppermint-liqueur.webp',
    ingridientDescription: 'Peppermint liqueur is a clear and refreshing spirit that is made by infusing peppermint leaves in alcohol. It has a bold and minty flavor, with a subtle sweetness and a refreshing cooling sensation. In cocktails and mixology, peppermint liqueur is often used as an ingredient to add a burst of minty freshness and depth to drinks. It pairs well with cream-based liqueurs in creamy cocktails, as well as with citrus and fruity flavors in more complex cocktails. Its versatility makes it a popular choice for both classic and modern drinks, and its vibrant green color adds a pop of brightness to any mixology creation.',
    componentText: "Welcome to our exciting journey through the captivating world of cocktails featuring the vibrant and refreshing hero of the hour: Peppermint Rum! If you're on the hunt for that perfect drink to invigorate your taste buds, dive into our curated collection of recipes tailored for every occasion. From festive gatherings to cozy nightcaps, peppermint rum brings a unique twist to your cocktail creations. Add a splash of minty magic to your mixology adventures with our easy-to-follow, delicious, and crowd-pleasing recipes. Let's raise our glasses to exploring the endless possibilities that peppermint rum has to offer! Cheers to unforgettable flavors waiting to be discovered.",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#angostura-Bitters',
    componentName: 'Angostura Bitters',
    ingridientName: 'angostura-bitters',
    ingridientCategory: 'Mixer',
    ingridientOrigin: 'Trinidad and Tobago',
    ingridientInvented: '1824',
    ingridientStrenght: '0%',
    ingridientBackgroundImg: 'img/ShakeIngridients/angostura.webp',
    ingridientDescription: 'Angostura Bitters is a concentrated bitters made from a variety of botanicals and spices, including gentian root and cinnamon. With its signature reddish-brown color and complex flavor profile, it has become a staple ingredient in many classic and modern cocktails. Its intense and aromatic taste adds depth and complexity to drinks, while also balancing out sweetness and enhancing other flavors. Whether used as a few dashes in a traditional Old Fashioned or in more experimental concoctions, Angostura Bitters is a versatile and essential ingredient in mixology.',
    componentText: "Welcome to the vibrant world of cocktails where Angostura Bitters reign supreme as the secret ingredient that elevates drinks from good to unforgettable. Whether you're a mixology maestro or a home bartender, these timeless bitters add depth, complexity, and a hint of mystery to every concoction. From refreshing summer sippers to cozy winter warmers, Angostura Bitters are versatile, enhancing both classic and modern recipes. Dive into our curated list of cocktails that showcase this indispensable ingredient, and discover your new favorite drink today!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#honey',
    componentName: 'Honey',
    ingridientName: 'honey',
    ingridientCategory: 'Kitchen cupboard',
    ingridientOrigin: '',
    ingridientInvented: '',
    ingridientStrenght: '0%',
    ingridientBackgroundImg: 'img/ShakeIngridients/honey.jpg',
    ingridientDescription: "Honey is a sweet, viscous substance created by bees from the nectar of flowers. Used for centuries as a natural sweetener and ingredient in cooking and baking, honey has also found its way into the world of cocktails and mixology. Its complex yet delicate flavor adds depth and dimension to drinks, while its thick consistency can help balance out stronger flavors. From classic cocktails, such as the Bee's Knees, to modern twists, honey is a versatile and essential component in the creation of delicious and unique libations.",
    componentText: "Discover the sweet allure of cocktails made with honey, your natural ticket to elevating your mixology game! Dive into our curated collection of honey-infused concoctions, perfect for those seeking to blend the rich, comforting taste of honey with diverse spirits and flavors. From refreshing summer sippers to cozy winter warmers, our recipes cater to all seasons and occasions. Whether you're a mixology maestro or a cocktail curious newbie, get ready to stir, shake, and sip your way through the golden goodness of honey cocktails. Cheers to finding your next favorite drink!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#vodka',
    componentName: 'Vodka',
    ingridientName: 'vodka',
    ingridientCategory: 'Spirit',
    ingridientOrigin: 'Poland, Ukraine',
    ingridientInvented: '15th century',
    ingridientStrenght: '40%',
    ingridientBackgroundImg: 'img/ShakeIngridients/vodka.jpg',
    ingridientDescription: `Vodka is a distilled spirit known for its purity and neutrality, often characterized by its lack of discernible taste and aroma, which makes it a versatile base for a myriad of cocktails. Originating from the Slavic word "voda," meaning "water," vodka's name reflects its clear and clean characteristics. Historically, it is believed to have its roots in the regions of modern-day Russia, Poland, and Ukraine, although its precise origins are the subject of nationalistic debates. Over the centuries, vodka has played a significant cultural role in Eastern European societies, not just as a drink but also as a form of medicinal remedy and even a monetary medium in times of economic strife.`,
    componentText: "Welcome to our vibrant collection, where vodka takes center stage in our cocktail recipes, transforming your evenings into a symphony of flavors! Whether you're an aficionado searching for the next great mix or a beginner eager to embark on a mixology adventure, you'll find something here to ignite your passion. From classic concoctions to innovative twists, our vodka-infused selections promise to elevate your home bar experience. Dive into our easy-to-follow recipes, and let's shake things up together, one sip at a time. Cheers to memorable moments and exquisite tastes!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#almond-extract',
    componentName: 'Almond extract',
    ingridientName: 'almond-extract',
    ingridientCategory: 'Kitchen cupboard',
    ingridientOrigin: '',
    ingridientInvented: '',
    ingridientStrenght: '0%',
    ingridientBackgroundImg: 'img/ShakeIngridients/almond-extract.webp',
    ingridientDescription: 'Almond extract is a strong, concentrated liquid flavoring made from crushed almonds and alcohol. Its sweet, nutty aroma and taste make it a popular ingredient in cocktail and mixology recipes, adding a rich depth of flavor to drinks. The extract is typically used in small amounts to enhance the almond notes in a variety of cocktails, such as amaretto sours and almond margaritas, or to add a subtle almond twist to classic recipes like Old Fashioneds and Manhattans. Its versatility and intense flavor make almond extract a staple in the arsenal of mixologists and bartenders.',
    componentText: "Almond extract is a strong, concentrated liquid flavoring made from crushed almonds and alcohol. Its sweet, nutty aroma and taste make it a popular ingredient in cocktail and mixology recipes, adding a rich depth of flavor to drinks. The extract is typically used in small amounts to enhance the almond notes in a variety of cocktails, such as amaretto sours and almond margaritas, or to add a subtle almond twist to classic recipes like Old Fashioneds and Manhattans. Its versatility and intense flavor make almond extract a staple in the arsenal of mixologists and bartenders.",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#triple-Sec',
    componentName: 'Triple Sec',
    ingridientName: 'triple-sec',
    ingridientCategory: 'Liqueur',
    ingridientOrigin: 'France',
    ingridientInvented: '1850s',
    ingridientStrenght: '40%',
    ingridientBackgroundImg: 'img/ShakeIngridients/triple-sec.webp',
    ingridientDescription: 'Triple Sec is a clear and highly versatile liqueur that is an essential ingredient in many popular cocktails. It is made from the peels of sweet and bitter oranges and has a strong orange flavor with a subtle sweetness. Its high alcohol content, typically around 40%, adds a kick to drinks and helps to balance out other ingredients. Triple Sec is commonly used as a sweetener and flavor enhancer in a wide range of cocktails, including Margaritas, Cosmopolitans, and Long Island Iced Teas. Its ability to blend well with other spirits and ingredients makes it a staple in mixology and a must-have for any well-stocked bar.',
    componentText: "Dive into the vibrant world of cocktails with our Triple Sec-infused recipes, a key ingredient that brings a delightful orange zest to any drink. Whether you're shaking up a classic Margarita, crafting a sophisticated Cosmopolitan, or exploring the fruity delights of a Mai Tai, Triple Sec is your go-to liqueur for enhancing flavor and adding a touch of sweetness. Ideal for cocktail enthusiasts and newcomers alike, our recipes are simple to follow, guaranteeing a perfect mix of fun and flavor in every glass. Cheers to discovering your next favorite Triple Sec cocktail!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#blueberries',
    componentName: 'Blueberries',
    ingridientName: 'blueberries',
    ingridientCategory: 'Kitchen cupboard',
    ingridientOrigin: '',
    ingridientInvented: '',
    ingridientStrenght: '0%',
    ingridientBackgroundImg: 'img/ShakeIngridients/blueberries.jpg',
    ingridientDescription: 'Blueberries are small succulent berries with a bluish-purple color and a slightly sweet and tart taste. They are commonly used in cocktails and mixology to add a burst of vibrant color and a bold, fruity flavor. They can be muddled, pureed, or used as a garnish to enhance the flavor profile of drinks and give them a visually appealing touch. Blueberries are also a popular ingredient in many fruity and refreshing summer cocktails, making them a versatile and delicious addition to any drink.',
    componentText: "Dive into the delicious world of blueberry cocktails, where every sip is bursting with sweet, tangy flavors and a gorgeous, eye-catching hue. Whether you're shaking up a storm for a summer party or crafting a cozy drink for a chill evening, our collection is brimming with irresistible blueberry cocktail recipes just waiting to be discovered. From refreshing mojitos to sophisticated martinis, these vibrant concoctions are perfect for any occasion, promising to impress your taste buds and elevate your mixology skills. Let's get mixing and make your bar the berry best it can be!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#white_vermouth',
    componentName: 'White vermouth',
    ingridientName: 'white-vermouth',
    ingridientCategory: 'Wine and champagne',
    ingridientOrigin: 'Italy, France, Spain',
    ingridientInvented: '1796',
    ingridientStrenght: '16%',
    ingridientBackgroundImg: 'img/ShakeIngridients/white-vermouth.webp',
    ingridientDescription: 'White vermouth is a type of fortified wine that is commonly used in cocktails and mixology. It is made by infusing white wine with a variety of botanicals, herbs, and spices, and then fortified with a neutral spirit. This results in a slightly sweet and herbaceous flavor profile that is commonly used as a base in classic cocktails such as the Martini, Negroni, and Manhattan. White vermouth adds depth, complexity, and a unique flavor profile to cocktails, making it a versatile and essential ingredient in mixology.',
    componentText: "Embark on a journey through the sophisticated world of cocktails with White Vermouth as your guiding star. This versatile and aromatic vermouth is the backbone of many classic and modern mixology creations, promising to elevate your cocktail game. Whether you're searching for the perfect aperitif to impress your guests or craving a refreshing and elegant drink to unwind with, our curated selection of White Vermouth cocktails is your ultimate resource. Discover simple yet stunning recipes, expert tips, and the secret to mastering the art of vermouth-based cocktails. Cheers to exploring the endless possibilities with White Vermouth!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#cardamom-pods',
    componentName: 'Cardamom pods',
    ingridientName: 'cardamom-pods',
    ingridientCategory: 'Kitchen cupboard',
    ingridientOrigin: '',
    ingridientInvented: '',
    ingridientStrenght: '0%',
    ingridientBackgroundImg: 'img/ShakeIngridients/cardamom-pods.jpg',
    ingridientDescription: 'Cardamom pods are a type of spice that come from the seed pods of the cardamom plant. They have a distinctively strong, sweet and spicy taste and are commonly used in cocktails and mixology to add depth and complexity to drinks. When crushed or ground, they release a fragrant aroma and intense flavor, making them a perfect addition to many cocktails, such as the classic Old Fashioned or a refreshing gin and tonic. With their versatile nature, cardamom pods are a must-have ingredient for any mixologist looking to elevate their cocktail game.',
    componentText: "Cardamom pods are a type of spice that come from the seed pods of the cardamom plant. They have a distinctively strong, sweet and spicy taste and are commonly used in cocktails and mixology to add depth and complexity to drinks. When crushed or ground, they release a fragrant aroma and intense flavor, making them a perfect addition to many cocktails, such as the classic Old Fashioned or a refreshing gin and tonic. With their versatile nature, cardamom pods are a must-have ingredient for any mixologist looking to elevate their cocktail game.",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#grenadine',
    componentName: 'Grenadine',
    ingridientName: 'grenadine',
    ingridientCategory: 'Mixer',
    ingridientOrigin: 'France, Caribbean Netherlands',
    ingridientInvented: '1690',
    ingridientStrenght: '0%',
    ingridientBackgroundImg: 'img/ShakeIngridients/grenadine.jpg',
    ingridientDescription: "Grenadine is a deep red syrup made from pomegranate juice and sugar, commonly used in cocktails and mixology as a sweetener and to add a vibrant color. Its tart and fruity flavor profile pairs well with a variety of spirits and can be used in classic cocktails like the Shirley Temple or Tequila Sunrise, as well as more complex drinks such as the Hurricane. In mixology, grenadine is also often used to create layered drinks by slowly pouring it over the back of a spoon to create a gradient effect. Its versatility and ability to enhance flavors make it a must-have ingredient in any cocktail lover's bar.",
    componentText: "Welcome to our vibrant collection of cocktail recipes featuring the sweet and colorful Grenadine! Whether you're a mixology maestro or a casual enthusiast searching for easy-to-make beverages, our Grenadine-based concoctions will certainly delight. Grenadine, known for adding a touch of sweetness and a rich red hue, is indispensable for creating visually stunning and deliciously tempting drinks. From classic favorites to innovative new twists, our recipes cater to all tastes. Dive into our curated list and discover the magic Grenadine brings to cocktail crafting – perfect for any occasion!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#wkd-red',
    componentName: 'WKD Red',
    ingridientName: 'wkd-red',
    ingridientCategory: 'Kitchen cupboard',
    ingridientOrigin: '',
    ingridientInvented: '',
    ingridientStrenght: '0%',
    ingridientBackgroundImg: 'img/ShakeIngridients/wkd-red.webp',
    ingridientDescription: "WKD Red is a vibrant and refreshing alcoholic drink known for its bold red color and fruity taste. Its unique blend of fruit flavors, including raspberry, peach, and citrus, make it a popular choice for use in cocktails and mixed drinks. The sweetness of WKD Red adds a burst of flavor to any cocktail, making it a versatile and essential ingredient in mixology. Whether it's mixed with other spirits or enjoyed on its own over ice, WKD Red is the perfect addition to any cocktail menu.",
    componentText: "WKD Red is a vibrant and refreshing alcoholic drink known for its bold red color and fruity taste. Its unique blend of fruit flavors, including raspberry, peach, and citrus, make it a popular choice for use in cocktails and mixed drinks. The sweetness of WKD Red adds a burst of flavor to any cocktail, making it a versatile and essential ingredient in mixology. Whether it's mixed with other spirits or enjoyed on its own over ice, WKD Red is the perfect addition to any cocktail menu.",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#white-rum',
    componentName: 'White rum',
    ingridientName: 'white-rum',
    ingridientCategory: 'Spirit',
    ingridientOrigin: 'Jamaica, Puerto Rico, Cuba',
    ingridientInvented: '1700s',
    ingridientStrenght: '40%',
    ingridientBackgroundImg: 'img/ShakeIngridients/white-rum.jpg',
    ingridientDescription: "White rum, also known as light or silver rum, is a type of clear distilled alcohol that is made from sugarcane juice or molasses. It has a light and smooth flavor profile, making it a popular choice for cocktails and mixology. White rum is often used as a base spirit in tropical drinks, such as mojitos, daiquiris, and piña coladas. Its versatility allows it to be paired with a wide range of ingredients, from fresh fruits and juices to bitters and liqueurs, making it an essential ingredient in a bartender's arsenal. Its crisp and clean taste makes it the perfect choice for a refreshing and flavorful cocktail.",
    componentText: "Welcome cocktail enthusiasts and rum aficionados! If you're on the hunt for top-notch recipes to craft delectable drinks using white rum, you've landed in the perfect spot. Dive into our collection where white rum takes center stage, offering a versatile base for a plethora of refreshing, zesty, and iconic cocktails. Whether you're gearing up for a sophisticated soiree or just looking to unwind with a tropical twist, our carefully curated selection promises to elevate your mixology game and introduce you to the finest blends. Cheers to discovering your new favorite white rum cocktail!",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#rumChata',
    componentName: 'Rumchata',
    ingridientName: 'rumchata',
    ingridientCategory: 'Liqueur',
    ingridientOrigin: 'United States',
    ingridientInvented: '2010',
    ingridientStrenght: '14%',
    ingridientBackgroundImg: 'img/ShakeIngridients/rumchata.webp',
    ingridientDescription: 'RumChata is a creamy and versatile liquor that is made from a blend of Caribbean rum, real dairy cream, and natural cinnamon, vanilla, and sugar flavors. It has a smooth and sweet taste with hints of spice, making it a popular choice for cocktails and mixology. Its rich and creamy texture adds depth and complexity to cocktails, while its cinnamon and vanilla notes complement a variety of different flavors. Whether enjoyed on its own over ice or mixed into a decadent dessert-inspired cocktail, RumChata is a must-try for any mixologist looking to elevate their creations.',
    componentText: "RumChata is a creamy and versatile liquor that is made from a blend of Caribbean rum, real dairy cream, and natural cinnamon, vanilla, and sugar flavors. It has a smooth and sweet taste with hints of spice, making it a popular choice for cocktails and mixology. Its rich and creamy texture adds depth and complexity to cocktails, while its cinnamon and vanilla notes complement a variety of different flavors. Whether enjoyed on its own over ice or mixed into a decadent dessert-inspired cocktail, RumChata is a must-try for any mixologist looking to elevate their creations.",
  },
  { 
    componentImage: 'img/ShakeIngridients/shakeSprite.svg#cointreau',
    componentName: 'Cointreau',
    ingridientName: 'cointreau',
    ingridientCategory: 'Liqueur',
    ingridientOrigin: 'France',
    ingridientInvented: '1849',
    ingridientStrenght: '40%',
    ingridientBackgroundImg: 'img/ShakeIngridients/cointreau.webp',
    ingridientDescription: 'Cointreau is a premium French liqueur known for its complex and distinctly bitter orange flavor. Made from a blend of sweet and bitter orange peels and a neutral spirit base, it adds a bright and citrusy element to cocktails. Its versatility and balanced sweetness make it a staple in mixology, adding depth and character to classic drinks such as margaritas, cosmopolitans, and sidecars. Its smooth texture and bold flavor also make it a popular choice for creating unique and refreshing cocktails.',
    componentText: "Dive into the spirited world of cocktails with Cointreau, your key to unlocking a treasure trove of mixology magic. Whether you're a professional bartender or a home cocktail enthusiast, our curated collection of Cointreau-based cocktails features easy-to-follow recipes that promise to add a touch of elegance to any gathering. From classic mixes to innovative concoctions, let the unique orange flavor of Cointreau elevate your drink repertoire. Perfect for festive celebrations or a cozy night in, discover how Cointreau can transform your cocktail creations into unforgettable experiences. Cheers to your next masterful mix!",
  },
];