# Generated by Django 5.1 on 2024-08-28 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="birthdate",
            new_name="birth_date",
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=datetime.date(1992, 6, 13), max_length=65, unique=True
            ),
            preserve_default=False,
        ),
    ]
