# Generated by Django 5.1 on 2024-11-01 13:04

import barmeister.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=barmeister.models.tag_ingredient_file_path,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CocktailRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "cocktail_type",
                    models.CharField(
                        choices=[
                            ("Low-Alcoholic", "Low Alcoholic"),
                            ("Non-Alcoholic", "Non Alcoholic"),
                            ("Strong", "Strong"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "taste",
                    models.CharField(
                        choices=[
                            ("Sweet", "Sweet"),
                            ("Sour", "Sour"),
                            ("Bitter", "Bitter"),
                            ("Salty", "Salty"),
                            ("Creamy", "Creamy"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "cocktail_base",
                    models.CharField(
                        choices=[
                            ("Vodka", "Vodka"),
                            ("Brandy", "Brandy"),
                            ("Whiskey", "Whiskey"),
                            ("Gin", "Gin"),
                            ("Tequila", "Tequila"),
                            ("Rum", "Rum"),
                            ("Wine", "Wine"),
                            ("Sparkling Wine", "Sparkling Wine"),
                            ("Juice", "Juice"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("Long Drink", "Long Drink"),
                            ("Short Drink", "Short Drink"),
                            ("Shot", "Shot"),
                            ("Sour", "Sour"),
                            ("Classic", "Classic"),
                            ("Hot", "Hot"),
                        ],
                        max_length=100,
                    ),
                ),
                ("how_to_make", models.TextField()),
                ("preparation_time", models.IntegerField(help_text="Time in minutes")),
                (
                    "preparation_method",
                    models.CharField(
                        choices=[
                            ("Build", "Build"),
                            ("Shake", "Shake"),
                            ("Stir", "Stir"),
                            ("Blend", "Blend"),
                            ("Layer", "Layer"),
                            ("Heat", "Heat"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=barmeister.models.photo_cocktail_file_path
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CocktailIngredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("gr", "G"),
                            ("ml", "Ml"),
                            ("slice", "Slice"),
                            ("pcs", "Piece"),
                            ("tablespoon", "Tablespoon"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=0, max_digits=5)),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cocktail_ingredients",
                        to="barmeister.cocktailrecipe",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_in_cocktails",
                        to="barmeister.ingredient",
                    ),
                ),
            ],
            options={
                "unique_together": {("cocktail", "ingredient")},
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("commented_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="barmeister.cocktailrecipe",
                    ),
                ),
            ],
            options={
                "ordering": ["-commented_at"],
            },
        ),
        migrations.AddField(
            model_name="cocktailrecipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="barmeister.CocktailIngredients", to="barmeister.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="cocktailrecipe",
            name="tags",
            field=models.ManyToManyField(blank=True, to="barmeister.tag"),
        ),
        migrations.CreateModel(
            name="FavouriteCocktails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourites",
                        to="barmeister.cocktailrecipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "unique_together": {("user", "cocktail")},
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stars",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "One"),
                            (2, "Two"),
                            (3, "Three"),
                            (4, "Four"),
                            (5, "Five"),
                        ],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="barmeister.cocktailrecipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "cocktail")},
            },
        ),
    ]
