# Generated by Django 5.1 on 2024-09-03 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("barmeister", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cocktailrecipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="cocktailingredients",
            name="cocktail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cocktail_ingredients",
                to="barmeister.cocktailrecipe",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="cocktail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="barmeister.cocktailrecipe",
            ),
        ),
        migrations.AddField(
            model_name="favouritecocktails",
            name="cocktail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourites",
                to="barmeister.cocktailrecipe",
            ),
        ),
        migrations.AddField(
            model_name="favouritecocktails",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cocktailrecipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="barmeister.CocktailIngredients", to="barmeister.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="cocktailingredients",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_in_cocktails",
                to="barmeister.ingredient",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favouritecocktails",
            unique_together={("user", "cocktail")},
        ),
        migrations.AlterUniqueTogether(
            name="cocktailingredients",
            unique_together={("cocktail", "ingredient")},
        ),
    ]
