# Generated by Django 5.1 on 2024-09-17 06:23

import barmeister.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barmeister", "0004_alter_ingredient_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=barmeister.models.tag_ingredient_file_path,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cocktailrecipe",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="barmeister.tag"),
        ),
    ]
